apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "sptribs-shared-infrastructure"
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_j_to_z/sptribs-shared-infrastructure
    github.com/project-slug: hmcts/sptribs-shared-infrastructure
  tags:
    - terraform
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=special-tribunals-builds
      title: "#special-tribunals-builds on Slack"
      icon: chat
spec:
  type: service
  lifecycle: production
  owner: dcd_sptribs
